Add Tinkers OreDict Cache
TheUsefulLists/UsefulMods pull request #141
Opened 2022-10-09 08:18 UTC by TheAirBlow

> Tinkers' Construct scans all recipes to register ore dictory based smelting recipes, such as golden sword => 288mB molten gold. However, there are thousands of recipes in massive modpacks. The game would scan them every game loading and take much time. This mod caches all smelting recipes and stops Tinkers' Construct scanning all recipes over and over again. Performance optimization would appear on the second load.

2022-10-09 14:37 UTC, NordicGamerFE commented
Add Tinkers OreDict Cache in alphabetical order

2022-10-10 12:01 UTC, lrmtheboss requested changes
All additions to a list must be done in alphabetical order, Please move it to the correct location.

2022-10-10 12:01 UTC, lrmtheboss commented on Performance/Performance112.md
> +| [Tinkers OreDict Cache](https://www.curseforge.com/minecraft/mc-mods/tinkers-oredict-cache) | Unknown | This mod caches tinkers construct melting recipes to speed up game loading time | youyihj | B
It needs to be added in alphabetical order

2023-04-17 13:38 UTC, lrmtheboss commented
Closing due to being stale

2023-04-17 13:38 UTC, closed without merging